### PR TITLE
complete mapping up to `nadd`

### PR DESCRIPTION
**Pull request by AnthonyBordg**

### CODE REVIEW

**Comment by fblanqui** [comment]
Hi Anthony. I get the following error:
```
File "./thm1106571_term_abbrevs.v", line 6, characters 114-116:
Error:
In environment
a0 : Type'
x0 : a0
x1 : type0 a0
x2 : type1 a0
y0 : type1 a0
The term "x1" has type "type0 a0" while it is expected to have type
 "a0 -> bool" (cannot unify "Prop" and "bool").
```

**Comment by fblanqui** [comment]
This can be solved by adding:
```
Definition bool_of_Prop (P:Prop) : bool := COND P true false.
Coercion bool_of_Prop: Sortclass >-> bool.
```
which generates the following warning though:
```
Warning:
New coercion path [bool_of_Prop; is_true] : Sortclass >-> Sortclass is not definitionally an identity function.
New coercion path [is_true; bool_of_Prop] : bool >-> bool is not definitionally an identity function.
[ambiguous-paths,coercions,default]
```

**Comment by fblanqui** [comment]
I fixed things in hd and EL but there is still some error:
```
File "./thm1105686.v", line 9, characters 14-20:
Error:
In environment
_25569 : Type'
The term "EL_def" has type
 "EL =
  ε
    (fun EL' : nat * nat -> nat -> list _25569 -> _25569 =>
     forall _18015 : nat * nat,
     (forall l : list _25569, EL' _18015 (coq.NUMERAL 0) l = hd l) /\
     (forall (n : nat) (l : list _25569),
      EL' _18015 (S n) l = EL' _18015 n (List.tl l)))
    (coq.NUMERAL (BIT1 (BIT0 (BIT1 (BIT0 (BIT0 (BIT0 (BIT1 0))))))),
     coq.NUMERAL (BIT0 (BIT0 (BIT1 (BIT1 (BIT0 (BIT0 (BIT1 0))))))))"
while it is expected to have type "EL = term0 _25569"
(cannot unify "ε
                 (fun EL' : nat * nat -> nat -> list _25569 -> _25569 =>
                  forall _18015 : nat * nat,
                  (forall l : list _25569,
                   EL' _18015 (coq.NUMERAL 0) l = hd l) /\
                  (forall (n : nat) (l : list _25569),
                   EL' _18015 (S n) l = EL' _18015 n (List.tl l)))
                 (coq.NUMERAL
                    (BIT1 (BIT0 (BIT1 (BIT0 (BIT0 (BIT0 (BIT1 0))))))),
                  coq.NUMERAL
                    (BIT0 (BIT0 (BIT1 (BIT1 (BIT0 (BIT0 (BIT1 0))))))))" and
"term0 _25569").
```
You also need to map TL to tl.
Can you please do this?

**Comment by AnthonyBordg** [comment]
@fblanqui I mapped `TL` to `tl` as requested, though please note that this can't be done directly, since `List.tl nil := nil` while `TL nil`doesn't reduce to anything else. Thus, I defined `Coq.tl`which coincides with `TL` on `nil` and with `List.tl` on `cons h t` and then proved that `@tl A = @TL A` for any `A: Type'`. Is it what you had in mind?

**Pull request merged**
